service: otel-splunk-layer
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: secretsmanager:GetSecretValue
          Resource: "*"

layers:
  scriptsLayer:
    path: scripts-layer

functions:
  api:
    handler: index.handler
    environment:
      OTEL_SERVICE_NAME: "test"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=test,deployment.environment=dev"
      OTEL_LOG_LEVEL: "ERROR"
      OTEL_PROPAGATORS: "tracecontext"
      AWS_LAMBDA_EXEC_WRAPPER: "/opt/wee"
      OTEL_TRACES_SAMPLER: "always_on"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "http/protobuf"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "https://ingest.au0.signalfx.com/v2/trace/otlp"
      OTEL_TRACES_EXPORTER: "otlp"
    layers:
      - !Ref ScriptsLayerLambdaLayer # Reference the layer you created
      - arn:aws:lambda:ap-southeast-1:254067382080:layer:splunk-apm:87
    events:
      - httpApi:
          path: /
          method: get
