#!/bin/bash

eval "$(node /opt/getSecret.js)"
echo "Splunk access token set"
echo $SPLUNK_ACCESS_TOKEN
# eval "$(node ./getSecret.js)"
export NODE_OPTIONS="${NODE_OPTIONS} --require /opt/wrapper.js"

if [[ $OTEL_RESOURCE_ATTRIBUTES != *"service.name="* ]]; then
export OTEL_RESOURCE_ATTRIBUTES="service.name=${AWS_LAMBDA_FUNCTION_NAME},${OTEL_RESOURCE_ATTRIBUTES}"
fi

exec "$@"
